
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flbvmomloxdwjjgurncc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsYnZtb21sb3hkd2pqZ3VybmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNTc0NDgsImV4cCI6MjA1NzgzMzQ0OH0.lku6fe4hSXu2CUE9eX5h3dhwlsLszayyo3niIgnq_UI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create type definitions for our custom RPC functions
type RPCFunctions = {
  get_bush_fa_foia_data: () => Promise<any[]>;
  get_bush_fa_foia_data_paginated: (params: { 
    p_from: number; 
    p_to: number; 
    p_search: string | null;
  }) => Promise<any[]>;
  get_schema_info: () => Promise<any>;
}

// Extend the Supabase client type
type SupabaseClientWithRPC = ReturnType<typeof createClient<Database>> & {
  rpc<T extends keyof RPCFunctions>(
    fn: T,
    ...args: Parameters<RPCFunctions[T]> extends [infer P] ? [P] : []
  ): ReturnType<ReturnType<typeof createClient>['rpc']>;
};

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY
) as SupabaseClientWithRPC;

/**
 * NOTE: To use custom schema tables (outside of 'public'), 
 * you should create RPC functions on the Supabase server:
 * 
 * Example RPC Functions to create in Supabase:
 * 
 * - get_bush_fa_foia_data(): 
 *   Returns all records from bush_fa.foia table
 * 
 * - get_bush_fa_foia_data_paginated(p_from int, p_to int, p_search text): 
 *   Returns paginated records from bush_fa.foia with optional search
 * 
 * - get_schema_info():
 *   Returns schema information for debugging
 */

/**
 * Helper for cross-schema access to bush_fa.foia
 * Note: This is a fallback that uses RPC when available
 */
export const getBushFaFoiaData = async () => {
  try {
    // Try to call the RPC function
    const { data, error } = await supabase.rpc('get_bush_fa_foia_data');
    
    if (error) throw error;
    return { data, error: null };
  } catch (error) {
    console.error('Error fetching bush_fa.foia data:', error);
    return { data: null, error: error as Error };
  }
};

// Use RPC to access cross-schema data
export const getBushFaFoiaDataPaginated = async (from: number, to: number, search?: string) => {
  try {
    console.log('Fetching data with params:', { from, to, search });
    
    // Use RPC function to access cross-schema data
    const { data, error } = await supabase.rpc('get_bush_fa_foia_data_paginated', {
      p_from: from,
      p_to: to,
      p_search: search || null
    });
    
    if (error) throw error;
    
    // Get total count for pagination
    const countResponse = await getBushFaFoiaData();
    const totalCount = countResponse.data ? countResponse.data.length : 0;
    
    console.log('Fetched data count:', data?.length);
    return { data: data || [], error: null, count: totalCount };
  } catch (error) {
    console.error('Error fetching paginated foia data:', error);
    return { data: null, error: error as Error, count: 0 };
  }
};
