
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flbvmomloxdwjjgurncc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsYnZtb21sb3hkd2pqZ3VybmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNTc0NDgsImV4cCI6MjA1NzgzMzQ0OH0.lku6fe4hSXu2CUE9eX5h3dhwlsLszayyo3niIgnq_UI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

/**
 * NOTE: To use custom schema tables (outside of 'public'), 
 * you should create RPC functions on the Supabase server:
 * 
 * Example RPC Functions to create in Supabase:
 * 
 * - get_bush_fa_foia_data(): 
 *   Returns all records from bush_fa.foia table
 * 
 * - get_bush_fa_foia_data_paginated(p_from int, p_to int, p_search text): 
 *   Returns paginated records from bush_fa.foia with optional search
 * 
 * - get_schema_info():
 *   Returns schema information for debugging
 */

/**
 * Helper for cross-schema access to bush_fa.foia
 * Note: This is a fallback that uses RPC when available
 */
export const getBushFaFoiaData = async () => {
  try {
    // Try to call the RPC function
    const { data, error } = await supabase.rpc('get_bush_fa_foia_data' as any);
    
    if (error) throw error;
    return { data, error: null };
  } catch (error) {
    console.error('Error fetching bush_fa.foia data:', error);
    return { data: null, error: error as Error };
  }
};

export const getBushFaFoiaDataPaginated = async (from: number, to: number, search?: string) => {
  try {
    // Try to call the RPC function
    const { data, error } = await supabase.rpc('get_bush_fa_foia_data_paginated' as any, { 
      p_from: from, 
      p_to: to,
      p_search: search || null
    });
    
    if (error) throw error;
    return { data, error: null, count: data ? data.length : 0 };
  } catch (error) {
    console.error('Error fetching paginated bush_fa.foia data:', error);
    return { data: null, error: error as Error, count: 0 };
  }
};
