// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flbvmomloxdwjjgurncc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsYnZtb21sb3hkd2pqZ3VybmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNTc0NDgsImV4cCI6MjA1NzgzMzQ0OH0.lku6fe4hSXu2CUE9eX5h3dhwlsLszayyo3niIgnq_UI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);